# Generated by Django 4.2.2 on 2023-06-26 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('ioc', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_num', models.IntegerField()),
                ('best_of', models.PositiveSmallIntegerField()),
                ('match_round', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('handedness', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('A', 'Ambi'), ('U', 'Unknown')], default='U', max_length=1)),
                ('ioc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenis.country')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rank', models.IntegerField()),
                ('points', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenis.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('W', 'Winner'), ('L', 'Loser')], max_length=1)),
                ('height', models.PositiveSmallIntegerField()),
                ('age', models.FloatField()),
                ('score', models.PositiveSmallIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenis.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenis.player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(through='tenis.PlayerMatchStats', to='tenis.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenis.tournament'),
        ),
    ]
