# Generated by Django 4.2.2 on 2023-06-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_round',
            new_name='round',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='playermatchstats',
            unique_together={('match', 'player')},
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='age',
        ),
    ]
