# Generated by Django 4.2.2 on 2023-06-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0002_rename_match_round_match_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
