# Generated by Django 4.2.2 on 2023-06-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0003_alter_player_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('player', 'date')},
        ),
    ]
