# Generated by Django 4.2.2 on 2023-06-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0005_tournament_level_tournament_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.CharField(max_length=10),
        ),
    ]
