# Generated by Django 4.2.2 on 2023-06-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0007_alter_playermatchstats_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermatchstats',
            name='score',
        ),
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
