# Generated by Django 4.2.2 on 2023-06-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0009_alter_tournament_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
