# Generated by Django 4.2.2 on 2023-07-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0010_alter_tournament_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dob',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
